#!/usr/bin/env bash

SCRIPT_PATH="$0"
ARGS="$@"
COMPOSER_DIR="$HOME/.bin"
COMPOSER_PATH="$COMPOSER_DIR/composer.phar"

if [ "$(whoami)" == 'root' ] ; then
    su -s /bin/bash - www-data -c "$SCRIPT_PATH $ARGS"
else

    if [ ! -f "$COMPOSER_PATH" ] ; then
        mkdir -p "$COMPOSER_DIR"
        cd "$COMPOSER_DIR"
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    #    php -r "if (hash_file('SHA384', 'composer-setup.php') === '61069fe8c6436a4468d0371454cf38a812e451a14ab1691543f25a9627b97ff96d8753d92a00654c21e2212a5ae1ff36') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
    fi

    bash -c "cd /var/www/symfony; $COMPOSER_PATH $ARGS"
fi
